spring:
  application:
    name: sqlGenerator
  # Default dev environment
  profiles:
    active: dev
  # swagger3 support
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # Database Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sqlfather
    username: root
    password: 123456
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://test.cvqcxj6a925n.ap-northeast-1.rds.amazonaws.com:3306/test
#    username: admin
#    password: 1234567811
server:
  address: 0.0.0.0
  port: 8102
  servlet:
    context-path: /api
    # session expires in 30 days
    session:
      timeout: "P30D"
      cookie:
        same-site: none
        secure: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # Entity field name for global logical deletion
      logic-delete-value: 1 # Logical deleted value (default is 1)
      logic-not-delete-value: 0 # Logical undeleted value (default is 0)